#!/bin/bash
# usage: make_client_p12 coluser 9
openssl genrsa -out $1.key 1024
openssl req -new -key $1.key -out $1.csr
openssl x509 -req -days 365 -in $1.csr -CA ca.crt -CAkey ca.key -set_serial $2 -out $1.crt
openssl pkcs12 -export -out $1.pfx -inkey $1.key -in $1.crt -certfile ca.crt
